project:
  type: website
  output-dir: docs
  render:
    - pages/*.ipynb
    - pages/*.qmd
    - slides/*.qmd
    # - jupyter-demo.ipynb

website:
  title: "Exploring LLMs for Teaching and Learning"
  site-url: https://virtuelleakademie.github.io/promptly-literate
  repo-url: https://github.com/virtuelleakademie/promptly-literate
  # repo-actions: [edit, issue]
  favicon: /assets/robot.png
  open-graph: true
  search:
    location: navbar
    type: overlay
    # type: textbox
  twitter-card:
    creator: "@awellis"
    card-style: summary_large_image

  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    # logo: /assets/robot.png
    background: primary
    left:
      - text: "📚 Programm"
        file: pages/index.qmd

      - text: "📺 Slides"
        menu:
          - text: "Part 1"
            file: slides/workshop-slides-1.qmd


      - text: "🎓 Tutorials"
        menu:
          - text: "Natural language processing"
            href: pages/text-representation.ipynb
          - text: "How does an LLM work?"
            file: pages/about.qmd
          - text: "ChatGPT vs Playground"
            file: pages/about.qmd
          - text: "How to use LLMs: Prompting"
            file: pages/about.qmd
          - text: "Prompts for teaching and learning"
            file: pages/about.qmd


      - text: "💼 Activities"
        menu:
          - text: "Exploring ChatGPT/Playground"
            file: pages/about.qmd
          - text: "Prompting: basics"
            file: pages/about.qmd
          - text: "Prompting: roles"
            file: pages/about.qmd
          - text: "Develop an Assistant"
            file: pages/about.qmd

      - text: "🛠️ Resources"
        menu:
          - text: "Ratgeber"
            file: pages/resources.qmd
          - text: "Tools"
            file: pages/tools.qmd

    tools:
      - icon: robot
        text: Assistant
        file: pages/assistant.qmd
      - icon: lightbulb-fill
        text: Knowledge Base
        href: https://virtuelleakademie.ch/knowledge-base/
      # - icon: twitter
      #   href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/virtuelleakademie/promptly-literate/
          - text: Report a Bug
            url:  https://github.com/virtuelleakademie/promptly-literate/issues

page-footer:
    right:
    - icon: github
      href: https://github.com/virtuelleakademie/promptly-literate

format:
  html:
    theme:
      light:
      - cosmo
      - styles/theme-light.scss
      dark:
      - cosmo
      - styles/theme-dark.scss
    toc: true
    link-external-newwindow: true

execute:
  cache: true
  freeze: false
  execute-dir: project

editor:
  render-on-save: true
