project:
  type: website
  output-dir: docs
  render:
    # - pages/*.ipynb
    - pages/*.qmd
    - slides/*.qmd
    # - jupyter-demo.ipynb

website:
  title: "LLMs for Teaching and Learning"
  site-url: https://virtuelleakademie.github.io/promptly-literate
  repo-url: https://github.com/virtuelleakademie/promptly-literate
  # repo-actions: [edit, issue]
  favicon: /assets/robot.png
  open-graph: true
  search:
    location: navbar
    type: overlay
    # type: textbox
  twitter-card:
    creator: "@awellis"
    card-style: summary_large_image

  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    # logo: /assets/robot.png
    background: primary
    left:
      # - text: "🏠 Home"
      #   file: pages/index.qmd
      - text: "📚 Schedule"
        file: pages/programme.qmd

      - text: "📺 Slides"
        menu:
          - text: "Introduction"
            file: slides/00-introduction.qmd
          - text: "Part 1: Text representation, training and text generation"
            file: slides/01-text-representation-generation.qmd
          - text: "Part 2: Prompting techniques"
            file: slides/02-prompting-techniques.qmd
          - text: "Part 3: Prompting for learning and teaching"
            file: slides/03-prompting-learning-teaching.qmd
          - text: "Part 4: Reflection"
            file: slides/04-reflection.qmd



      - text: "🎓 Tutorials"
        menu:
          - text: "Text representation: embeddings"
            file: pages/text-representation.qmd
          # - text: "How does text generation work?"
          #   file: pages/text-generation.ipynb
          # - text: "ChatGPT vs Playground"
          #   file: pages/chatgpt-playground.ipynb
          - text: "Using the API: Prompting Programmatically"
            file: pages/prompting.qmd
          # - text: "Prompts for teaching and learning"
          #   file: pages/about.qmd


      - text: "💼 Activities"
        menu:
          - text: "Activity 1: Exploring LLMs"
            file: pages/activity-1-explore-llms.qmd
          - text: "Activity 2: Prompting techniques"
            file: pages/activity-2-prompting-techniques.qmd
          - text: "Activity 3: Prompting for teaching and learning"
            file: pages/activity-3-prompting-learning-teaching.qmd
          # - text: "Develop an Assistant"
          #   file: pages/about.qmd

      - text: "🛠️ Resources"
        menu:
          - text: "Ratgeber"
            file: pages/resources.qmd
          - text: "Tools"
            file: pages/tools.qmd

    tools:
      - icon: robot
        text: Assistant
        file: pages/assistant.qmd
      - icon: lightbulb-fill
        text: Knowledge Base
        href: https://virtuelleakademie.ch/knowledge-base/
      # - icon: twitter
      #   href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/virtuelleakademie/promptly-literate/
          - text: Report a Bug
            url:  https://github.com/virtuelleakademie/promptly-literate/issues

page-footer:
    right:
    - icon: github
      href: https://github.com/virtuelleakademie/promptly-literate

format:
  html:
    theme:
      light:
      - cosmo
      - styles/theme-light.scss
      dark:
      - cosmo
      - styles/theme-dark.scss
    toc: true
    link-external-newwindow: true

execute:
  cache: true
  freeze: false
  execute-dir: project

editor:
  render-on-save: true
