---
title: "Activity 1: Basic Prompting Techniques"
description: |
  Programming a GPT model.
date: last-modified
date-format: "DD MMM, YYYY"
author: 
  - name: Andrew Ellis
    url: https://github.com/awellis
    affiliation: Virtuelle Akademie, Berner Fachhochschule
    affiliation-url: https://virtuelleakademie.ch
    orcid: 0000-0002-2788-936X
license: CC BY
citation: true
bibliography: ../bibliography.bib
format:
    html:
        toc: true
        code-fold: true
        code-link: true
jupyter: python3
execute: 
  cache: false
  keep-ipynb: true
code-annotations: select
---



In this activity, you can explore various prompting guides for LLMs. They more or less all converge on the same set of techniques. You can then use these techniques to write your own prompts.

## Tasks

(@) **Explore prompting**. Use both/either ChatGPT and Copilot. If you want to look anything up, try these prompting guides:

:::{.callout-tip collapse="true"}
## Learn prompting: An comprehensive (and free) guide aimed at non-technical users.
{{< bi link >}} [Learn prompting](https://learnprompting.org/docs/intro)

```{=html}
<iframe src="https://learnprompting.org/docs/intro" width="100%" height="500px"></iframe>
``` 
:::


:::{.callout-tip collapse="true"}
## Prompting guide: A more technical guide to prompting
{{< bi link >}} [Prompting guide](https://www.promptingguide.ai/): **DAIR.AI** (Democratizing Artificial Intelligence Research, Education, and Technologies). The guide is licensed under an MIT license.

```{=html}
<iframe src="https://www.promptingguide.ai/" width="100%" height="500px"></iframe>
``` 
:::


:::{.callout-tip collapse="true"}
## SPARK
👉 [SPARK: a retrieval-augmented chatbot](https://huggingface.co/spaces/amagastya/SPARK): Chatbot that uses various prompting guides as its knowledge base.

<!-- ```{=html}
<iframe src="https://huggingface.co/spaces/amagastya/SPARK" width="100%" height="500px"></iframe>
```  -->
:::

(@) **Write a prompt** that will make ChatGPT or Copilot act as an argumentation critic.

You can use this as your starting point, and then iteratively improve it.

:::aside
Your first step could be to translate this into German:
👉 [Open in ChatGPT](https://chat.openai.com/share/bdfbf353-d06c-48fb-a291-6232e6e2c52e)
:::

:::{.callout-tip collapse="true"}
## Feedback on a text
I want you to act as a critic. Criticize what I give to you and show me where my argumentation is lacking. Start by asking me what text I would like feedback on. Then give me your feedback.
:::

<!-- I want you to act as a harsh critic. Criticize what I give to you and show me where my argumentation is lacking. Start by asking me what text I would like feedback on. Then ask me questions about my context to create the best feedback possible. If you feel you have all the context necessary, think step by step when creating your feedback. -->

If you need (badly written) essay, you can use this one:

:::{.callout-note collapse="true"}
## Badly written essay

Sollten Schulnoten abgeschafft werden?

In unserer heutigen Bildungswelt gibt es viele verschiedene Methoden, um den Fortschritt und das Wissen eines Schülers zu messen. Eine der gebräuchlichsten Methoden sind Schulnoten. Aber sollten wir wirklich Noten verwenden, um den Wert eines Schülers zu bestimmen? Ich glaube, dass Noten in Schulen abgeschafft werden sollten, und hier sind meine Gründe dafür:

Erstens, Noten sind oft subjektiv. Verschiedene Lehrer haben unterschiedliche Meinungen darüber, was eine "A" -Arbeit im Vergleich zu einer "B" -Arbeit ist. Ein Schüler könnte in einem Fach bei einem Lehrer eine "A" bekommen und bei einem anderen Lehrer eine "B". Dies zeigt, dass Noten nicht immer ein genaues Bild von dem Wissen eines Schülers geben.

Zweitens, Noten erzeugen unnötigen Druck. Viele Schüler fühlen sich durch die Noten, die sie bekommen, gestresst und überfordert. Dieser Druck kann zu Angstzuständen, Depressionen und anderen gesundheitlichen Problemen führen. Wenn es keine Noten gäbe, könnten sich die Schüler mehr auf das Lernen konzentrieren und weniger darauf, eine bestimmte Note zu bekommen.

Drittens, durch die Abschaffung von Noten könnten Schüler mehr Freiheit in ihrer Bildung haben. Sie könnten Themen studieren, die sie wirklich interessieren, anstatt sich darauf zu konzentrieren, welche Themen ihnen die besten Noten bringen würden. Dies könnte zu einer besseren und umfassenderen Bildung führen.

Einige könnten argumentieren, dass Noten notwendig sind, um den Fortschritt eines Schülers zu messen. Aber es gibt viele andere Möglichkeiten, den Fortschritt zu messen, wie zum Beispiel Portfolios, Präsentationen oder Projekte. Diese Methoden könnten ein genaueres Bild von dem Wissen und den Fähigkeiten eines Schülers geben.

Abschließend glaube ich, dass Schulnoten mehr Schaden als Nutzen bringen. Sie sind oft subjektiv, erzeugen unnötigen Druck und beschränken die Freiheit der Schüler. Es ist an der Zeit, dass wir ein neues System finden, um den Fortschritt und das Wissen unserer Schüler zu messen.
:::





(@) **Reflection**: Did your prompt work? What worked well? What didn't work well? 



## Prompting Guidelines

OpenAI give a set of strategies for using their models 

:::aside
[👉 Six strategies](https://platform.openai.com/docs/guides/gpt-best-practices/six-strategies-for-getting-better-results) 
:::

These include:

- writing clear instructions
- providing reference texts
- splitting tasks into subtasks
- giving GPT 'time to think'
- using external tools


Some general techniques are:

- Numbered Steps: For sequential tasks.
- Use delimiters: To separate info (e.g. `"`, \`,, `'`, `|`, `#`, ...).
- Few-shot prompting: Use a few examples for guidance.
- Chain-of-thought: Interconnected prompts.
- Role-based: Make the model assume a role (e.g. act like a tutor or advisor).
- Iterate and refine prompts. Choose your final prompt and use it in a new chat.



Combining these techniques, a template prompt for an LMM might look like this:

:::{.callout-tip}
## Template
1) Role: who is being simulated?
2) Task: what is to be done?
3) Steps: what are the steps to complete the task?
4) Context: what is the context of the task?
5) Goal: what is the goal of the task?
6) Format: what is the format of the output?
:::





<!-- 
:::{.callout-caution}
## Discussion 💬 

- What experiences did you have with prompting?
- Did you find any of the techniques particularly useful?
::: -->

