---
title: "Activity 2: Basic Prompting Techniques"
description: |
  Programming a GPT model.
date: last-modified
date-format: "DD MMM, YYYY"
author: 
  - name: Andrew Ellis
    url: https://github.com/awellis
    affiliation: Virtuelle Akademie, Berner Fachhochschule
    affiliation-url: https://virtuelleakademie.ch
    orcid: 0000-0002-2788-936X
license: CC BY
citation: true
bibliography: ../bibliography.bib
format:
    html:
        toc: true
        code-fold: true
        code-link: true
jupyter: python3
execute: 
  cache: false
  keep-ipynb: true
code-annotations: select
---

## Basic techniques


In this activity, you can explore various prompting guides for GPT models. They more or less all converge on the same set of techniques.

## Tasks

- Explore prompting, using both ChatGPT and the Playground. 
- Try the PromptTools Playground.
- Try out SPARK. This is a good demonstration of using a knowledge base and document retrieval can allow you to create a QA tool.

:::{.callout-tip}
## Prompts

Try revisiting the prompts you created in the previous activity. Given you current knowledge, can you improve them?
:::


## Prompting Guides

The general techniques are:

:::{.callout-note}
## Prompting Techniques
- Numbered Steps: For sequential tasks.
- Delimiters: To separate info (e.g. `"`, \`,, `'`, `|`, `#`, ...).
- Few-shot prompting: Use a few examples for guidance.
- Chain-of-thought: Interconnected prompts.
- Role-based: Make the model assume a role (e.g. act like a tutor or advisor).
- Success Tip: Iterate and refine prompts for peak performance.
:::



Combining these techniques, a template prompt for an LMM might look like this:

:::{.callout-note}
1) Role: who is being simulated?
2) Task: what is to be done?
3) Steps: what are the steps to complete the task?
4) Context: what is the context of the task?
5) Goal: what is the goal of the task?
6) Format: what is the format of the output?
:::


An example prompt for a chatbot might look like this:

:::{.callout-note}
## Feedback on a text
`I want you to act as a harsh critic. Criticize what I give to you and show me where my argumentation is lacking. Start by asking me what text I would like feedback on. Then ask me questions about my context to create the best feedback possible. If you feel you have all the context necessary, think step by step when creating your feedback.`
:::

## Explore Prompting Guides

- [Learn prompting](https://learnprompting.org/docs/intro): An incredibly comprehensive (and free) guide aimed at non-technical users.

- [Prompting guide](https://www.promptingguide.ai/): This is an excellent prompting guide by **DAIR.AI**
(Democratizing Artificial Intelligence Research, Education, and Technologies). The guide is licensed under an MIT license.

- [PromptTools Playground](https://prompttools.streamlit.app/): a web app that lets you play with various prompting techniques. You can use different LLMs, and even compare the results.


- [SPARK: a retrieval-augmented chatbot](https://huggingface.co/spaces/amagastya/SPARK). It uses various prompting guides as its knowledge base.



:::{.callout-caution}
## Discussion 💬 

- What experiences did you have with prompting?
- Did you find any of the techniques particularly useful?
:::

