---
title: "Notes"
---

## Qualitätszirkel Gesundheit

Mögliche Inhalte: Kurz, was kann man sich unter KI vorstellen Was sind Chat GPT oder andere tools Elicit, Bild Generatoren. Welche Auswirkungen hat KI auf das Lernen, auf die Lehre Etc.

Wie besprochen sende ich dir zwei Aufträge zu schriftlichen Arbeiten, die unsere Studierenden als Kompetenznachweis zu Hause erledigen. -- Modulabschlussarbeit im Modul Forschungsanwendung: **Formulieren einer Forschungsfrage**, **Literaturrecherche** auf wissenschaftlichen Datenbanken, Studien auswählen, **Qualität einschätzen**, Ergebnisse darstellen, **Synthese**, Diskussion, Schlussfolgerungen. -- Schriftliche Reflexionsarbeit basierend auf einem Kommunikationstraining: siehe Punkte 1-11 (Anhang Schriftliche Reflexionsarbeit). Der Anhang Kommunikationstraining ist als Hintergrundinfo gedacht. -- Bachelor These (kein Anhang): Viele Studierende verfassen eine systematische Literaturarbeit ausgehend von einer Fragestellung. Die Arbeit umfasst: Abstract, Einleitung, Fragestellung, Ziele, Theoretischer Bezugsrahmen, Methode, Ergebnisse, Diskussion, Schlussfolgerungen

## Notes

-   Can GPT think?
    -   what is thinking?
    -   System 1 vs System 2
    -   deliberative vs reflexive
    -   planning: timescales or 1-step-ahead
-   Creativity?
-   Consciousness?
-   Agent?
-   epistemic vs instrumental
-   what is a goal?

## Isaac Asimov's "Three Laws of Robotics"

The best known set of laws are Isaac Asimov's "Three Laws of Robotics". These were introduced in his 1942 short story "Runaround", although they were foreshadowed in a few earlier stories. The Three Laws are:

```         
A robot may not injure a human being or, through inaction, allow a human being to come to harm.
A robot must obey the orders given it by human beings except where such orders would conflict with the First Law.
A robot must protect its own existence as long as such protection does not conflict with the First or Second Laws.
```